from datetime import datetime
from pathlib import Path
from typing import Dict

from pptx import Presentation


def _add_title_slide(prs: Presentation, title: str, subtitle: str) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    slide.placeholders[1].text = subtitle


def _add_bullet_slide(prs: Presentation, title: str, body: str) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = title
    slide.shapes.placeholders[1].text = body[:3000]


def generate_ppt(title: str, sections: Dict[str, str], output_dir: str = "presentations") -> str:
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    prs = Presentation()
    _add_title_slide(
        prs,
        title=title,
        subtitle=f"Generated by NeuroPilot AI | {datetime.now().strftime('%Y-%m-%d %H:%M')}",
    )
    for section_title, content in sections.items():
        _add_bullet_slide(prs, section_title, str(content))

    filename = f"neuropilot_presentation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
    output_path = Path(output_dir) / filename
    prs.save(output_path)
    return str(output_path)
