from datetime import datetime
from pathlib import Path

from docx import Document


def generate_docx_report(title: str, sections: dict, output_dir: str = "reports") -> str:
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    doc = Document()
    doc.add_heading(title, level=1)
    doc.add_paragraph(f"Generated by NeuroPilot AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}")

    for section_title, content in sections.items():
        doc.add_heading(section_title, level=2)
        if isinstance(content, list):
            for item in content:
                doc.add_paragraph(str(item), style="List Bullet")
        else:
            doc.add_paragraph(str(content))

    filename = f"neuropilot_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    path = Path(output_dir) / filename
    doc.save(path)
    return str(path)
